#!/bin/bash

#first
#This file looks through all the files in the current
#directory for the string POSIX, and then prints the names of
#those files to the standard output.

IFS=''
echo "$0 $1 $2"
echo $*
echo $@
exit 0
